
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 24 18:37:23 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 18;
  public static final int READ = 16;
  public static final int IDENT = 27;
  public static final int PLUS = 2;
  public static final int RBRACE = 3;
  public static final int RPAREN = 4;
  public static final int FINDANY = 25;
  public static final int EQUAL = 5;
  public static final int CHAR = 28;
  public static final int SEMI = 6;
  public static final int PERIOD = 10;
  public static final int LPAREN = 7;
  public static final int LBRACE = 8;
  public static final int INC = 21;
  public static final int COMMA = 9;
  public static final int NUMBER = 26;
  public static final int EOF = 0;
  public static final int RSQUAR = 24;
  public static final int PROG = 11;
  public static final int DEC = 22;
  public static final int MINUS = 17;
  public static final int CONST = 14;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int SOLIDUS = 19;
  public static final int NEW = 15;
  public static final int BOOL = 29;
  public static final int LSQUAR = 23;
  public static final int VOID = 13;
  public static final int MODULUS = 20;
}

